import { Check, Gauge, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";

import { PageHeader } from "@/components/page-header";

export default function BillingPage() {
  return <div className="space-y-8"><PageHeader title="Billing & usage" description="Demo subscription presentation only. No Stripe integration, checkout, payment collection, or subscription enforcement exists."/><section className="grid gap-6 xl:grid-cols-[1fr_1.35fr]"><article className="rounded-xl bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center justify-between"><span className="rounded-lg bg-teal-400/15 p-2.5 text-teal-300"><ShieldCheck aria-hidden="true" size={22}/></span><span className="rounded-full border border-teal-400/20 bg-teal-400/10 px-3 py-1 text-xs font-semibold text-teal-300">Demo plan</span></div><p className="mt-6 text-sm text-slate-400">Current plan</p><h2 className="mt-1 text-2xl font-semibold">Surface Monitor</h2><p className="mt-3 text-sm leading-6 text-slate-400">Illustrative plan for ongoing external exposure visibility.</p><ul className="mt-6 space-y-3 text-sm text-slate-300"><Feature>50 monitored assets</Feature><Feature>20 simulated scans / month</Feature><Feature>90-day presentation history</Feature></ul></article><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-lg bg-teal-50 p-2.5 text-teal-700"><Gauge aria-hidden="true" size={20}/></span><div><h2 className="font-semibold text-slate-950">Current usage</h2><p className="mt-0.5 text-xs text-slate-500">Synthetic values for layout demonstration</p></div></div><div className="mt-7 space-y-6"><Usage label="Monitored assets" value="24 of 50" percent={48}/><Usage label="Monthly scans" value="12 of 20" percent={60}/><Usage label="Report previews" value="4 of 10" percent={40}/></div><div className="mt-7 rounded-lg border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-500">Usage is not measured or enforced. No payment data can be entered in this milestone.</div></article></section></div>;
}

function Feature({ children }: { children: ReactNode }) { return <li className="flex items-center gap-3"><Check aria-hidden="true" className="text-teal-400" size={16}/>{children}</li>; }
function Usage({ label, value, percent }: { label: string; value: string; percent: number }) { return <div><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{label}</span><span className="text-slate-500">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-label={label} aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-teal-600" style={{ width: `${percent}%` }}/></div></div>; }
